### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate

### ISSUE THREAD

**Issue by Eisorak** [ranahanocka/MeshCNN#105]
Hi @ranahanocka  

I tried the res_pool at [ 140.000, 100.000, 80.000 ] for a mesh (250 000 edges) but it gives me this error:
RuntimeError: CUDA out of memory. Tried to allocate 1.62 GiB (GPU 0; 8.00 GiB total capacity; 3.97 GiB already allocated; 1.25 GiB free; 4.68 GiB reserved in total by PyTorch).

Did you come across this error before?

but when I put small mesh it works perfectly.

**Comment by duhau** [comment]
Has the problem been solved? I have the same problem when the res_pool at [5578 4184 2788] for a mesh （6972 edges）.

**Comment by duhau** [comment]
Has the problem been solved? I have the same problem when the res_pool at [5578 4184 2788] for a mesh （6972 edges）.

**Comment by Eisorak** [comment]
To solve the problem you need to increase the VRAM memory with another GPU, or resize the meshes for edge reduction. 
in my case I reduced the meshes size and it works.

also think about reducing the batch_size, it can solve your problem.
